baseURL = "https://grassjournal.co"
title   = "Grass Journal"

languageCode = "en-us"
theme = "hello-friend-ng"
images = "mountain.png"

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"
# Adds blog image folder to the global site image search
staticDir = ["static", "content/posts/img"]

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false


# Directory name of your blog content (default is `content/posts`)
contentTypeName = "posts"
# Default theme "light" or "dark"
defaultTheme = "dark"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "01-02-2006"
  dateformNumTime = "Mon, Jan 2, 2006"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Hudson Gardner"
  keywords = "blog, buddhism, spirituality, minimalism, photography, meditation, philosophy, gardening"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"


[languages]
  [languages.en]
    title = "Grass Journal"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "○ Home"
      logoHomeLink = "/"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "who"
    name       = "Who"
    url        = "/who"
    weight     = "2"
  [[menu.main]]
    identifier = "grass"
    name       = "Grass"
    url        = "/grass"
    weight     = "2"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
    weight     = "3"
